version: '3.8'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - braas-network
    environment:
      - VITE_API_URL=http://video-description-service:5000
    depends_on:
      - video-description-service

  video-description-service:
    build:
      context: .  # Changed to root context to access common and secrets
      dockerfile: microservices/video-description-service/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ollama_data:/root/.ollama  # Persist Ollama models
    networks:
      - braas-network
    environment:
      - OLLAMA_HOST=http://localhost:11434
      - OLLAMA_ORIGINS=http://localhost:3000,http://localhost:5000

  # Video generation service will be added here later
  # video-generation-service:
  #   build: ...

volumes:
  ollama_data:  # Persistent volume for Ollama models
    name: ollama_data

networks:
  braas-network:
    name: braas-network 